services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "unless-stopped"
    ports:
      - "7001:7001"
    env_file:
      - .env
    volumes:
      - logs:/app/logs

volumes:
  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: var/log/bot_seller